### ISSUE TITLE
markdown 上的标题没有被加上data-id

### ISSUE THREAD

**Issue by whhlulu** [parksben/markdown-navbar#2]
markdown 上的标题没有被加上data-id
data-id是在哪个环节加上的？
找到问题了，你的代码严格行不够，在window上面md文件首行出现mac回车符会不能附加data-id

**Comment by parksben** [comment]
感谢反馈，能否将问题说明更详细些呢？方便的话希望提供您的用例。
如果是逻辑严密性的问题，我将在新版本更新。

**Comment by jzbbobo** [comment]
用您的组件加上react-markdown生成的导航点击不会跳转，路由这边我们需要一些设置么？

**Comment by parksben** [comment]
> 用您的组件加上react-markdown生成的导航点击不会跳转，路由这边我们需要一些设置么？

能够详细描述症结，最好能提供下你的用例？

**Comment by jzbbobo** [comment]
@parksben 我发现是这样的，没有配上样式，参照您博客的配了下样式点击可以跳转了。现在有个现象是这样的，我有一个页面左测是菜单栏，点击菜单会获取对应的文章显示，文章渲染是用的react-markdown，还用了您这个插件做页面锚点跳转。现在是点击菜单后获取新的content。问题是现在页面可以渲染但是会出现点击导航没法跳转，出现 Uncaught TypeError: Cannot read property 'offsetTop' of null
    at :3000/static/js/bundle.js:157728

**Comment by parksben** [comment]
1.0.8 版本已解决此问题

**Comment by hjp-h** [comment]
点击菜单不会跳转到对应的位置
