### ISSUE TITLE
一级标签生成错误

### ISSUE THREAD

**Issue by xvanning** [parksben/markdown-navbar#20]
不知道是不是我不会用，一级标签，目录总是会少一个标题。 删除第一个标题，会少第二个。 不删，第一个标题就没有。希望能修复一下。

**Comment by LaPoJ** [comment]
同样的问题

**Comment by parksben** [comment]
一级标签如果是 # 的话，我理解是文章标题。如果是文章正文的话，按照规范应该只有 ## 这样的二级标签才对。如果的确存在这种场景，我考虑先修复一下下。感谢反馈，祝大家工作顺利~！

**Comment by parksben** [comment]
使用上的理解偏差

**Comment by HuBoZhi** [comment]
如果确实想用一级标签作为标题的话，可以在文档前面加上"\n",就像这样：source={"\n" + this.state.mdBodyContent}

**Comment by HuBoZhi** [comment]
> 同样的问题

如果确实想用一级标签作为标题的话，可以在文档前面加上"\n",就像这样：source={"\n" + this.state.mdBodyContent}
