### ISSUE TITLE
TypeError: Cannot read property 'dataId' of undefined HTMLDocument.<anonymous>

### ISSUE THREAD

**Issue by slamdunkYYY** [parksben/markdown-navbar#21]
I got this error when I scroll the window: 

TypeError: Cannot read property 'dataId' of undefined HTMLDocument.<anonymous>

```
    229 | 
    230 | if (this.props.updateHashAuto) {
    231 |   // Hash changing callback
> 232 |   if (curHeading.dataId !== this.getCurrentHashValue()) {
    233 |  ^   this.props.onHashChange(curHeading.dataId, this.getCurrentHashValue());
    234 |   }
    235 | 
```

**Comment by 275044515** [comment]
> I got this error when I scroll the window:
> 
> TypeError: Cannot read property 'dataId' of undefined HTMLDocument.
> 
> ```
>     229 | 
>     230 | if (this.props.updateHashAuto) {
>     231 |   // Hash changing callback
> > 232 |   if (curHeading.dataId !== this.getCurrentHashValue()) {
>     233 |  ^   this.props.onHashChange(curHeading.dataId, this.getCurrentHashValue());
>     234 |   }
>     235 | 
> ```

the same issue using typescript

**Comment by parksben** [comment]
问题已解决，请更新到 1.4.2 版本。若仍问题望及时反馈~ 感谢~
