### ISSUE TITLE
h.innerText / t.text 需要trim之后对比  Cannot read property 'dataId' of undefined

### ISSUE THREAD

**Issue by summerscar** [parksben/markdown-navbar#22]
#21 https://github.com/parksben/markdown-navbar/issues/21

我也遇到了这个问题，打断点调试时发现在对比当前的文档位置时是  h.innerText === t.text 对比的，但是我发现我这份文档的标题末尾带有隐藏的字符（回车），我手动将整份文档的每一行trim之后，这个问题解决了。

**Comment by parksben** [comment]
感谢反馈和帮助定位问题，v1.4.2 版本的判断语句已经加上了 .trim() 方法
