### ISSUE TITLE
markdown里面没标题就直接报错了！

### ISSUE THREAD

**Issue by duziten** [parksben/markdown-navbar#24]
![image](https://user-images.githubusercontent.com/29852019/83354783-7f51b980-a38d-11ea-85da-9ca5f07b0210.png)

**Comment by parksben** [comment]
能否看下你的 md content？

**Comment by duziten** [comment]
这个问题应该很好复现吧随便一段内容，只要不写标题就可以出现

**Comment by parksben** [comment]
1.4.3 已修复
