### ISSUE TITLE
Can't resolve 'core-js'

### ISSUE THREAD

**Issue by lidachao111222** [parksben/markdown-navbar#25]
大佬，我是使用这个包的时候WEBPACK报错

ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.array.concat' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.array.concat' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.array.filter' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.array.filter' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.array.find' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.array.find' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.array.for-each' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.array.for-each' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.array.from' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.array.from' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.array.index-of' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.array.index-of' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.array.iterator' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.array.iterator' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.array.map' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.array.map' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.array.slice' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.array.slice' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.date.to-string' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.date.to-string' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.object.define-properties' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.object.define-properties' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.object.define-property' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.object.define-property' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.object.get-own-property-descriptor' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.object.get-own-property-descriptor' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.object.get-own-property-descriptors' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.object.get-own-property-descriptors' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.object.get-prototype-of' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.object.get-prototype-of' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.object.keys' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.object.keys' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.object.set-prototype-of' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.object.set-prototype-of' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.object.to-string' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.object.to-string' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.parse-int' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.parse-int' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.regexp.exec' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.regexp.exec' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.regexp.to-string' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.regexp.to-string' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.string.iterator' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.string.iterator' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.string.match' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.string.match' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.string.replace' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.string.replace' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.string.search' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.string.search' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.string.trim' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.string.trim' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.symbol' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.symbol' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.symbol.description' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.symbol.description' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.symbol.iterator' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/es.symbol.iterator' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/web.dom-collections.for-each' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/web.dom-collections.for-each' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/web.dom-collections.iterator' in '/Users/chaoli/Desktop/hello_eth/node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist'

If you're trying to use a package make sure that 'core-js/modules/web.dom-collections.iterator' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/_markdown-navbar@1.4.2@markdown-navbar/dist/index.js

failed Building development bundle - 11.475s

我是用的gatsby，进入index.js后其实core-js是能找到的。。。  google看了下说是core-js3的问题，有点懵，求大神解惑。

**Comment by lidachao111222** [comment]
https://codesandbox.io/s/happy-beaver-d3bhp?file=/src/pages/index.js

我在codesandbox里面装了这个包测试了 也出现了一样的问题。。。

**Comment by parksben** [comment]
这个问题应该是通过 github 的自动 pr 解决了。试了下你的 demo 貌似没复现了。
